
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.time.Duration;

public class Test1LoginCorrectoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    driver.manage().window().setSize(new Dimension(1920, 1080));
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void test1LoginCorrecto() throws InterruptedException {
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(20));

    driver.get("https://hmis-react-escudero.azurewebsites.net/");

    WebElement tituloLogin = wait.until(
        ExpectedConditions.visibilityOfElementLocated(By.xpath("//*[contains(text(),'Bienvenido de vuelta')]")));
    assertEquals("Bienvenido de vuelta", tituloLogin.getText());

    WebElement usuarioInput = wait.until(
        ExpectedConditions.visibilityOfElementLocated(By.cssSelector("input[type='text']")));
    usuarioInput.clear();
    usuarioInput.sendKeys("usuario");

    WebElement passwordInput = wait.until(
        ExpectedConditions.visibilityOfElementLocated(By.cssSelector("input[type='password']")));
    passwordInput.clear();
    passwordInput.sendKeys("hola00");

    WebElement botonLogin = wait.until(
        ExpectedConditions.elementToBeClickable(By.xpath("//button[contains(., 'Iniciar Sesión')]")));

    js.executeScript("arguments[0].scrollIntoView({block: 'center'});", botonLogin);
    Thread.sleep(500);
    js.executeScript("arguments[0].click();", botonLogin);

    WebElement tituloProyectos = wait.until(
        ExpectedConditions.visibilityOfElementLocated(By.xpath("//*[contains(text(),'Proyectos Activos')]")));
    assertEquals("Proyectos Activos", tituloProyectos.getText());
  }
}
