
// Generated by Selenium IDE and adapted for JUnit WebDriver
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;

import java.time.Duration;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class Test10EliminarProyectoIncorrectoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  private JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    driver.manage().window().setSize(new Dimension(1920, 1080));
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void test10EliminarProyectoIncorrecto() throws InterruptedException {
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(25));

    driver.get("https://hmis-react-escudero.azurewebsites.net/");

    WebElement tituloLogin = wait.until(
        ExpectedConditions.visibilityOfElementLocated(
            By.xpath("//*[contains(text(),'Bienvenido de vuelta')]")));
    assertEquals("Bienvenido de vuelta", tituloLogin.getText());

    WebElement usuarioInput = wait.until(
        ExpectedConditions.visibilityOfElementLocated(By.cssSelector("input[type='text']")));
    usuarioInput.clear();
    usuarioInput.sendKeys("usuario");

    WebElement passwordInput = wait.until(
        ExpectedConditions.visibilityOfElementLocated(By.cssSelector("input[type='password']")));
    passwordInput.clear();
    passwordInput.sendKeys("hola00");

    WebElement botonLogin = wait.until(
        ExpectedConditions.elementToBeClickable(By.xpath("//button[contains(., 'Iniciar Sesión')]")));
    js.executeScript("arguments[0].scrollIntoView({block: 'center'});", botonLogin);
    Thread.sleep(500);
    js.executeScript("arguments[0].click();", botonLogin);

    WebElement tituloProyectos = wait.until(
        ExpectedConditions.visibilityOfElementLocated(
            By.xpath("//*[contains(text(),'Proyectos Activos')]")));
    assertEquals("Proyectos Activos", tituloProyectos.getText());

    List<WebElement> proyectoInexistente = driver.findElements(
        By.xpath("//h3[contains(text(),'Proyecto Inexistente Selenium')]"));

    assertEquals(
        "No debe existir un proyecto inexistente para eliminar",
        0,
        proyectoInexistente.size());

    List<WebElement> botonesAccederProyecto = wait.until(
        ExpectedConditions.presenceOfAllElementsLocatedBy(
            By.xpath("//*[contains(text(),'Acceder al Proyecto')]")));

    assertTrue(
        "El listado debe seguir mostrando proyectos activos tras el intento incorrecto",
        botonesAccederProyecto.size() > 0);
  }
}