
// Generated by Selenium IDE and adapted for JUnit WebDriver
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;

import java.time.Duration;
import java.util.HashMap;
import java.util.Map;

public class Test11RegistroCorrectoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  private JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    driver.manage().window().setSize(new Dimension(1920, 1080));
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void test11RegistroCorrecto() throws InterruptedException {
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));

    String usuarioRegistro = "seleniumuser" + System.currentTimeMillis();
    String passwordRegistro = "hola00";

    driver.get("https://hmis-react-escudero.azurewebsites.net/");

    WebElement tituloLogin = wait.until(
        ExpectedConditions.visibilityOfElementLocated(
            By.xpath("//*[contains(text(),'Bienvenido de vuelta')]")));
    assertEquals("Bienvenido de vuelta", tituloLogin.getText());

    WebElement botonRegistroInicial = wait.until(
        ExpectedConditions.elementToBeClickable(
            By.xpath(
                "//*[contains(text(),'Regístrate') or contains(text(),'Registrate') or contains(text(),'Regístrate gratis')]")));

    js.executeScript("arguments[0].scrollIntoView({block: 'center'});", botonRegistroInicial);
    Thread.sleep(500);
    js.executeScript("arguments[0].click();", botonRegistroInicial);

    WebElement tituloRegistro = wait.until(
        ExpectedConditions.visibilityOfElementLocated(
            By.xpath("//*[contains(text(),'Crea tu cuenta')]")));
    assertEquals("Crea tu cuenta", tituloRegistro.getText());

    WebElement usuarioInput = wait.until(
        ExpectedConditions.visibilityOfElementLocated(By.cssSelector("input[type='text']")));
    usuarioInput.clear();
    usuarioInput.sendKeys(usuarioRegistro);

    WebElement passwordInput = wait.until(
        ExpectedConditions.visibilityOfElementLocated(By.cssSelector("input[type='password']")));
    passwordInput.clear();
    passwordInput.sendKeys(passwordRegistro);

    WebElement botonRegistrarse = wait.until(
        ExpectedConditions.elementToBeClickable(
            By.xpath("//button[contains(., 'Registrarse')]")));

    js.executeScript("arguments[0].scrollIntoView({block: 'center'});", botonRegistrarse);
    Thread.sleep(500);
    js.executeScript("arguments[0].click();", botonRegistrarse);

    WebElement tituloProyectos = wait.until(
        ExpectedConditions.visibilityOfElementLocated(
            By.xpath("//*[contains(text(),'Proyectos Activos')]")));

    assertEquals("Proyectos Activos", tituloProyectos.getText());
  }
}