
// Generated by Selenium IDE and adapted for JUnit WebDriver
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;

import java.time.Duration;
import java.util.HashMap;
import java.util.Map;

public class Test2LoginIncorrectoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  private JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    driver.manage().window().setSize(new Dimension(1920, 1080));
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void test2LoginIncorrecto() throws InterruptedException {
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(20));

    driver.get("https://hmis-react-escudero.azurewebsites.net/");

    WebElement tituloLogin = wait.until(
        ExpectedConditions.visibilityOfElementLocated(
            By.xpath("//*[contains(text(),'Bienvenido de vuelta')]")));
    assertEquals("Bienvenido de vuelta", tituloLogin.getText());

    WebElement usuarioInput = wait.until(
        ExpectedConditions.visibilityOfElementLocated(By.cssSelector("input[type='text']")));
    usuarioInput.clear();
    usuarioInput.sendKeys("usuarioIncorrecto");

    WebElement passwordInput = wait.until(
        ExpectedConditions.visibilityOfElementLocated(By.cssSelector("input[type='password']")));
    passwordInput.clear();
    passwordInput.sendKeys("contrasenaIncorrecta");

    WebElement botonLogin = wait.until(
        ExpectedConditions.elementToBeClickable(By.xpath("//button[contains(., 'Iniciar Sesión')]")));

    js.executeScript("arguments[0].scrollIntoView({block: 'center'});", botonLogin);
    Thread.sleep(500);
    js.executeScript("arguments[0].click();", botonLogin);

    WebElement tituloLoginDespues = wait.until(
        ExpectedConditions.visibilityOfElementLocated(
            By.xpath("//*[contains(text(),'Bienvenido de vuelta')]")));

    assertEquals("Bienvenido de vuelta", tituloLoginDespues.getText());
  }
}